### ISSUE TITLE
Function undefined error

### ISSUE THREAD

**Issue by notabeatle** [dougwollison/nlingual#15]
https://github.com/dougwollison/nlingual/blob/9ee8ba1e30641d18099a8e37ec7b33beb45a1803/includes/class-nlingual-rewriter.php#L452

I'm seeing undefined function fatal errors in my logs for the above line.

I believe that should be `get_the_author_posts_link`, with the `the`. I'd make a PR but it's so small a change that any workflow disruption (for you) of the PR flow seems not worth the hassle. If you'd prefer a PR, I can do that, no problem.

[Original proposal for the relevant function in WP, named as in line 452 but, apparently, modified after some comments](https://core.trac.wordpress.org/ticket/30355)

[Function docs](https://developer.wordpress.org/reference/functions/get_the_author_posts_link/)

**Comment by dougwollison** [comment]
Publishing a hotfix patch now. This was staight up a case of me not actually testing it since literally none of the sites I develop utilize author pages.

**Comment by notabeatle** [comment]
Don't rush it on my behalf. Judging from the frequency and the fact that I didn't think we were using those either, I'm pretty sure it was only being triggered by bots or search spiders on the site I'm seeing it on.

**Comment by dougwollison** [comment]
It's the simplest of fixes and frankly I'm so behind on other issues and bug fixes I'd like to get _one_ out of the way.
