### ISSUE TITLE
Multi-page post are broken

### ISSUE THREAD

**Issue by bdeshi** [dougwollison/nlingual#18]
Create a post with multiple pages using the **page break** block. Only the first page of this post is now accessible, the rest loops back to the first page.

**Comment by dougwollison** [comment]
Smeg, another feature that never sees use on the IRL projects I test this plugin on.

I've made some modifications to how the plugin handles canonical URLs, and tested it on a both a paginated front page and interior page; seems to be working correctly now, without breaking the handling on paginated archives.

I'm aiming to publish the new version to the repo early next week.
